### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

### ISSUE THREAD

**Issue by Schnei1811** [pesser/stable-diffusion#13]
Getting the following error following the instructions

python scripts/txt2img.py --prompt "a virus monster is playing guitar, oil on canvas" --ddim_eta 0.0 --n_samples 4 --n_iter 4 --scale 5.0  --ddim_steps 50
Traceback (most recent call last):
  File "scripts/txt2img.py", line 11, in <module>
    from pytorch_lightning import seed_everything
  File "C:\Users\Stefan\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "C:\Users\Stefan\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "C:\Users\Stefan\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "C:\Users\Stefan\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "C:\Users\Stefan\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (C:\Users\Stefan\anaconda3\envs\ldm\lib\site-packages\torchmetrics\utilities\data.py)

**Comment by Tariq195** [comment]
conda uninstall torchmetrics
conda install torchmetrics=0.5

**Comment by sixtyspam** [comment]
torchmetrics 0.7 worked for me, had same problem

pip uninstall torchmetrics
pip install torchmetrics==0.7

Don't forget to activate conda environment in case you're using conda
